from opto.features.priority_search.priority_search import PrioritySearch, Samples, ModuleCandidate
import copy
from opto.trainer.utils import  async_run
import time
from opto.trainer.algorithms.basic_algorithms import batchify
from opto.features.priority_search.utils import set_module_parameters, remap_update_dict, create_module_from_update_dict, is_module_copy

class DummyPrioritySearch(PrioritySearch):
    """ Disable the optimizer where llm is used to propose parameters. """
    def propose(self,
                samples : Samples,
                verbose : bool = False,
                **kwargs):
        """ Analyzing samples and propose new parameters using self.optimizer. An independent optimizer is used for the minibatch generated by one agent and generates n_proposals proposals.

        Args:
            samples (Samples): Samples collected by the exploration candidates. If None, the agent's parameters are returned without updating.
            verbose (bool, optional): Whether to print verbose output. Defaults to False.
            **kwargs: Additional keyword arguments that may be used by the implementation.

        Returns:
            candidates (list of ModuleCandidate): A list of proposed candidates for the next iteration.
        """
        print("--- Proposing new parameters...") if verbose else None
        assert isinstance(samples, Samples), "samples must be an instance of Samples."
        samples = samples.samples  # list of BatchRollout objects
        n_proposals = self.num_proposals  # number of proposals to generate per optimizer
        
        # Associate each BatchRollout with self._exploration_candidates
        matched_candidates_and_samples = self.match_candidates_and_samples(self._exploration_candidates, samples)
        # NOTE len(matched_candidates_and_samples) <= len(self._exploration_candidates) since some exploration candidates might be duplicated.
        candidate_batchrollouts_list = [ (k,b) for k, v in matched_candidates_and_samples.items() for b in v]
        assert len(samples) == len(candidate_batchrollouts_list), "All samples must be associated with exploration candidates."
        n_batches = len(samples)  # number of batch rollouts in the samples

        # need to copy optimizer for the n_batches
        def _backward(n):
            candidate, rollouts = candidate_batchrollouts_list[n]
            optimizer = candidate.optimizer or self.optimizer
            # Create a copy of the optimizer to avoid modifying the original one and to allow parallel execution
            optimizer = copy.deepcopy(optimizer)
            optimizer.parameters = rollouts.module.parameters()  # set the optimizer's parameters to the proposal's parameters
            targets = [r.target for r in rollouts]
            feedbacks = [r.feedback for r in rollouts]
            # batchify the targets and feedbacks
            target = batchify(*targets)
            feedback = batchify(*feedbacks).data  # str
            # standard optimizer step
            optimizer.zero_feedback()  # reset the optimizer's feedback
            optimizer.backward(target, feedback)  # compute the gradients based on the targets and feedbacks
            return optimizer

        args_list = [(n,) for n in range(n_batches)]
        optimizers = async_run([_backward]*n_batches,  # run the optimizer step for each agent in parallel
                                 args_list=args_list,
                                 max_workers=self.num_threads,  # use the number of threads specified in the class
                                 description='Backward')
        assert len(optimizers) == n_batches, "Number of optimizers must match number of batch rollouts."
        # need to copy optimizer for the n_proposals
        # NOTE when optimizer is deepcopied, its parameters are not copied.
        optimizers = [copy.deepcopy(o) for o in optimizers ] * n_proposals  # repeat args_list n_proposals times
        assert len(optimizers) == n_batches * n_proposals, "Number of optimizers must match number of batch rollouts times number of proposals."

        # For each optimizer, containing the backward feedback, we call it n_proposals times to get the proposed parameters.
        def _step(n):
            # return a dummy update dict without calling the optimizer
            update_dict = {}
            for param in self.agent.parameters():
                # values are random strings using time.time()
                # Make the random_string very long
                update_dict[param] = "random_string_" + str(time.time()) 
            update_dict = remap_update_dict(self.agent, update_dict)  # remap the update dict to the agent's parameters
            return update_dict  # return the proposed parameters

        args_list = [(n,) for n in range(n_batches*n_proposals)]
        update_dicts = async_run([_step]*n_batches*n_proposals,  # run the optimizer step for each agent in parallel
                                  args_list=args_list,
                                  max_workers=self.num_threads,  # use the number of threads specified in the class
                                  description=f"Calling optimizers: Generating {n_proposals} proposals for each of {n_batches} batches",)

        # update_dicts is a list of dicts of length n_batches * n_proposals
        # Create ModuleCandidate objects for each proposed update_dict that is non-trivial
        candidates = [ModuleCandidate(self.agent, update_dict, optimizer)
                        for update_dict, optimizer in zip(update_dicts, optimizers) if update_dict is not None]  # filter out None updates
        return candidates